### ISSUE TITLE
Reverse lookups too? (feature)

### ISSUE THREAD

**Issue by mixographer** [martindemello/cryptic-abbreviations#1]
It would be cool in you could also reverse search, like 

lookup> doctor 

| MD | DR | DOC |.........

I've forked it and I'll take a look. I know this is over a year old, so  you may not still be developing it.

**Comment by martindemello** [comment]
that's a nice idea :) i'd be happy to either do it myself or merge in a pull request for it

**Comment by mixographer** [comment]
I’ll try to understand it, and work on it, but if you know how it works, and it’s not a bother… 

I just saw you have a puzzle format converter, I was just thinking of that! I parse a bunch of .puz (text format) puzzles, but Cursewords only plays .puz (binary). I’ll try your tool for that purpose. Thanks!

**Comment by martindemello** [comment]
great, let me know if you have any feature requests for that one too :)

**Comment by mixographer** [comment]
One solution to this issue, would be to just structure the data in both ways ie:

zr: Zaire
zz: snoring
zz: sound of snoring
Doctor: D
Doctor: DR
Doctor: MD

But maybe it's better to read the dict both ways? 

(BTW pangrid works perfect for my use case!)

**Comment by martindemello** [comment]
a little more complicated than i expected, but done :) it just does a full text search in the definitions, so something like `and` will get a lot more hits than expected but works reasonably well for the most part.

**Comment by mixographer** [comment]
Great!

**Comment by mixographer** [comment]
I'm testing now, and I don't really understand why some defn don't work. If I search priest, I get p but if I search mountie, I don't get anything. I'm not sure what the difference is. 

Edit: Priest also gives me 'p' but not 'eli' and 'pr' which are in the lists.

**Comment by martindemello** [comment]
works for me:
```
lookup > priest
abbe: priest (French)
cure: priest (French)
eli: priest
pr: priest
rev: priest
 
lookup > mountie
mp: mountie
```

priest should not have given you `p` at all (just checked in chambers and it's actually correct, but it's not there in this repo yet!). could you try again with a clean checkout?

**Comment by mixographer** [comment]
You are correct! I messed something up, and fetching didn't fix it. I've deleted and re-clones and all is good.
